services:
    dh_userbundle.user_provider:
        class: DH\UserBundle\Security\UserProvider
        arguments: ["@doctrine", '@security.encoder_factory', '%dh_userbundle.user_class%']
        public: true

    dh_userbundle.user_manager:
        alias: DH\UserBundle\Model\UserManager
        public: true

    DH\UserBundle\Model\UserManager:
        arguments: ['@security.encoder_factory']
        public: true

    DH\UserBundle\Controller\SecurityController:
        calls:
            - method: setContainer
              arguments:
                  - '@service_container'
        public: true

    DH\UserBundle\Controller\PasswordController:
        calls:
            - method: setContainer
              arguments:
                  - '@service_container'
        public: true

    dh_userbundle.user_event_subscriber:
        class: DH\UserBundle\Event\UserEventSubscriber
        arguments: ['@dh_userbundle.user_manager']
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        public: true

    dh_userbundle.user_checker:
        class: DH\UserBundle\Security\UserChecker
        arguments: ['@doctrine']
        public: true

    dh_userbundle.mailer:
        class: DH\UserBundle\Mailer\TwigMailer
        arguments: ['@mailer', '@router', '@twig', { 'email_from': '%dh_userbundle.password_reset.email_from%' }]
        public: true
